### ISSUE TITLE
Course intro

### ISSUE THREAD

**Issue by karthik** [NHM-STARS/materials18#1]
Explicitly discuss how we are teaching and how they can follow along via live-coding, slides, online materials, typing, copy-paste, etc.

**Comment by nhcooper123** [comment]
I've added a markdown file with the list of topics we need to cover, feel free to add to this if I've missed anything. I'll lead this but you should feel free to chip in where needed.

**Comment by nhcooper123** [comment]
Also added my intro to R materials.
