### ISSUE TITLE
Create a pre-workshop survey

### ISSUE THREAD

**Issue by karthik** [NHM-STARS/materials18#18]
I'm happy to set this up but we need to decide on what questions to ask.

Rough brainstorming
- Previous R experience
- What OS
- What are you statistics gaps
- Packages you want to know about for current research and are struggling with

**Comment by nhcooper123** [comment]
I think that's probably it, that's all I ever ask people. 

Probably good to find out this stuff ASAP so if you're able to set it up soon(ish) that would be great. That way we can more easily incorporate it into the teaching. 

Also the stats question, can we ensure it says "the aim of this workshop is NOT to teach stats, but out of interest...". Good to manage expectations in advance.

**Comment by nhcooper123** [comment]
Also last year this survey was used to collect email addresses and send to students with download instructions - I think you organised this Karthik are you happy to do so again?

**Comment by karthik** [comment]
Happy to put this together. But can we get a list of questions here first?

name
email
previous R experience (likert scale)
what os
What stats gaps (for general info, not the focus of this workshop)
packages of interest
...

?

**Comment by nhcooper123** [comment]
Sorry, my first reply obviously wasn't clear. I meant yes those questions are enough. I wouldn't add anymore.Perhaps just add a "any other comments" option too for stuff people want to ask but don't see a place to do so in the form.

Or to do you me to fully write out questions and response options?

**Comment by karthik** [comment]
Done. Here is the URL: https://nhm-stars.github.io/materials18/misc/preworkshop

Feel free to send it to students anytime. I don't think there is any urgency to do it before late May.
