### ISSUE TITLE
Bigger open-ended exercise for data wrangling in R, active

### ISSUE THREAD

**Issue by karthik** [NHM-STARS/materials18#7]
Think about how to provide structured work time (tidy data, missing data, wrangling, filtering, summarizing, etc… )

**Comment by nhcooper123** [comment]
I've added one idea and a folder called `examples/` for collating these

**Comment by sarahsupp** [comment]
I also provided an example in Day 2 using the Portal dataset that should follow nicely on from the lessons on data wrangling, ggplot, and tidy data. I'm guessing it could be something students could work on anywhere from 30-60 minutes. But having some other examples, or types of data would be great! We could either do more than one exercise, and let this take lots of time, or we could possibly let students choose their own adventure or work in small subgroups for some pair programming, or peer advising, on one of agreed upon examples.
